### ISSUE TITLE
C++ application producing an empty trace

### ISSUE THREAD

**Issue by mackncheesiest** [ruhrie/TraceAtlas#36]
I'm not sure if there is some guidance with this, but I'm trying to trace a C++-based application, and while the bitcode seems to be getting annotated correctly with the basic block dump, etc, calls, the resulting trace is seemingly empty and produces nothing usable for cartographer/etc.

Has anyone here run into a similar issue when tracing C++ applications in the past? My first hunch would be that it's some subtlety around name mangling, but I'm not entirely sure.

It's an application with multiple source files, but I am choosing to only instrument and trace `main.cpp`, and my sequence of calls is essentially

```
clang++-9 -S -flto -fPIC -static main.cpp -o output-main.ll

opt-9 -load $TRACEHOME/lib/AtlasPasses.so \
  -EncodedTrace output-main.ll -S -o output-main-opt.ll

clang++-9 -static -fuse-ld=lld-9 -lpthread -lz -lm $TRACEHOME/lib/libAtlasBackend.a \
  <dependencies.cpp...> output-main-opt.ll -o output-main-tracer.out

./output-main-tracer.out
```

If further investigation is needed and it's not a simple fix, I'd be happy to provide the application I'm trying to trace.

**Comment by ruhrie** [comment]
So I haven't seen any issues with cpp at all. There are some issues in tik, but you aren't getting even close to that.

The primary thing that comes to mind is that the tracer gets started/terminated through ctors and dtors. Looking at the flags you are using in the first line, I'm not sure what the implications of using `-fPIC` and `-static` are. As a rule I advise using `-fuse-ld=lld-9 -Wl,--plugin-opt=emit-llvm` to generate llvm because it doesn't change any part of the compilation.

If you provide us with the bitcode/cpp causing the problem we can take a look, but if you aren't getting any output with the commands you are showing it is likely that your flags are curtailing the ctors/dtors. @benroywillis may have some thoughts on this as well though.

**Comment by mackncheesiest** [comment]
The `-fPIC` and `-static` flags are essentially just a requirement of, at the end of this, I'm usually targeting a shared object, and with some applications, compilation will fail if I don't pass those in during the initial frontend conversion to LLVM. A quick swap of the arguments used to produce the LLVM didn't give a fix at first glance.

Looking at the output from `opt`, the calls for `@OpenFile` and `@CloseFile` are in the `llvm.global_ctors` and `llvm.global_dtors` lists so presumably they are getting called, and the `raw.trc` file is actually being written to disk -- it just doesn't actually contain meaningful trace information.

I'll include the human readable LLVM output from `opt` below (renamed to .txt to get around github file type limitations...)
[output-main-opt.txt](https://github.com/ruhrie/TraceAtlas/files/4352587/output-main-opt.txt)

If everything looks good there and you'd like to try compiling the full application let me know

**Comment by ruhrie** [comment]
So looking at the bitcode I don't see any immediate problems. I tried to compile it down, but there were ~8 missing symbols. The next step to debug on our end is to compile it ourselves. From what I can tell the symbols missing appear to be matrix related, but I could be wrong on that.

Send over the cpp with compilation commands and we'll take a look.

**Comment by mackncheesiest** [comment]
Sent the source over email
